// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 14.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfImage uIItemImage = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom.UIItemImage;
            WpfTabPage uIКвестыTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIКвестыTabPage;
            WpfTabPage uIНавыкиTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIНавыкиTabPage;
            WpfTabPage uIХарактеристикиTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIХарактеристикиTabPage;
            WpfTabPage uIИнформацияTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIИнформацияTabPage;
            WpfButton uIOKButton = this.UIMyLifeRPGOrganizerXWindow.UIOKButton;
            WpfButton uIButtonFocusButton = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom1.UIButtonFocusButton;
            WpfButton uIОКButton = this.UIMyLifeRPGOrganizerXWindow.UIОКButton;
            WpfButton uIButtonFocusButton1 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom1.UIButtonFocusButton1;
            WpfListItem uISampleModelTaskListItem = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom2.UIItemList.UISampleModelTaskListItem;
            WpfButton uIРедактироватьзадачуButton = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom2.UIРедактироватьзадачуButton;
            WpfButton uIOKButton1 = this.UIMyLifeRPGOrganizerXWindow.UIUcTasksSettingsViewCustom.UIOKButton;
            WpfButton uIОКButton1 = this.UIMyLifeRPGOrganizerXWindow.UIОКButton1;
            #endregion

            // Щелкните рисунок
            Mouse.Click(uIItemImage, new Point(172, 121));

            // Щелкните "Квесты" вкладка
            Mouse.Click(uIКвестыTabPage, new Point(180, 11));

            // Щелкните "Навыки" вкладка
            Mouse.Click(uIНавыкиTabPage, new Point(141, 5));

            // Щелкните "Характеристики" вкладка
            Mouse.Click(uIХарактеристикиTabPage, new Point(139, 29));

            // Щелкните "Информация" вкладка
            Mouse.Click(uIИнформацияTabPage, new Point(151, 24));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton, new Point(733, 11));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton, new Point(558, 164));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton, new Point(889, 26));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton1, new Point(104, 200));

            // Щелкните "Sample.Model.Task" элемент списка
            Mouse.Click(uISampleModelTaskListItem, new Point(193, 200));

            // Щелкните "Редактировать задачу" кнопка
            Mouse.Click(uIРедактироватьзадачуButton, new Point(53, 28));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton1, new Point(606, 15));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton1, new Point(876, 17));
        }
        
        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfImage uIItemImage = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom.UIItemImage;
            WpfTabPage uIКвестыTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIКвестыTabPage;
            WpfTabPage uIНавыкиTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIНавыкиTabPage;
            WpfTabPage uIХарактеристикиTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIХарактеристикиTabPage;
            WpfTabPage uIИнформацияTabPage = this.UIMyLifeRPGOrganizerXWindow.UITabControlTabList.UIИнформацияTabPage;
            WpfButton uIOKButton = this.UIMyLifeRPGOrganizerXWindow.UIOKButton;
            WpfButton uIButtonFocusButton = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom1.UIButtonFocusButton;
            WpfButton uIОКButton = this.UIMyLifeRPGOrganizerXWindow.UIОКButton;
            WpfButton uIButtonFocusButton1 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom1.UIButtonFocusButton1;
            WpfListItem uISampleModelTaskListItem = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom2.UIItemList.UISampleModelTaskListItem;
            WpfButton uIРедактироватьзадачуButton = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom2.UIРедактироватьзадачуButton;
            WpfButton uIOKButton1 = this.UIMyLifeRPGOrganizerXWindow.UIUcTasksSettingsViewCustom.UIOKButton;
            WpfButton uIОКButton1 = this.UIMyLifeRPGOrganizerXWindow.UIОКButton1;
            WpfCustom uIUserControlCustom3 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom3;
            WpfImage uIItemImage1 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom11.UIItemImage;
            WpfButton uIButtonFocusButton2 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom21.UIButtonFocusButton;
            WpfButton uIButtonFocusButton11 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom22.UIButtonFocusButton1;
            WpfListItem uISampleModelTaskListItem1 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom31.UIItemList.UISampleModelTaskListItem;
            WpfButton uIРедактироватьзадачуButton1 = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom32.UIРедактироватьзадачуButton;
            WpfMenuItem uIВыходMenuItem = this.UIMyLifeRPGOrganizerXWindow.UIUserControlCustom4.UIItemMenu.UIВыходMenuItem;
            #endregion

            // Щелкните рисунок
            Mouse.Click(uIItemImage, new Point(172, 121));

            // Щелкните "Квесты" вкладка
            Mouse.Click(uIКвестыTabPage, new Point(180, 11));

            // Щелкните "Навыки" вкладка
            Mouse.Click(uIНавыкиTabPage, new Point(141, 5));

            // Щелкните "Характеристики" вкладка
            Mouse.Click(uIХарактеристикиTabPage, new Point(139, 29));

            // Щелкните "Информация" вкладка
            Mouse.Click(uIИнформацияTabPage, new Point(151, 24));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton, new Point(733, 11));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton, new Point(558, 164));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton, new Point(889, 26));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton1, new Point(104, 200));

            // Щелкните "Sample.Model.Task" элемент списка
            Mouse.Click(uISampleModelTaskListItem, new Point(193, 200));

            // Щелкните "Редактировать задачу" кнопка
            Mouse.Click(uIРедактироватьзадачуButton, new Point(53, 28));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton1, new Point(606, 15));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton1, new Point(876, 17));

            // Щелкните "UserControl" пользовательский элемент управления
            Mouse.Click(uIUserControlCustom3, new Point(632, 544));

            // Щелкните рисунок
            Mouse.Click(uIItemImage1, new Point(152, 86));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton, new Point(823, 16));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton2, new Point(532, 153));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton, new Point(874, 27));

            // Щелкните "ButtonFocus" кнопка
            Mouse.Click(uIButtonFocusButton11, new Point(184, 228));

            // Щелкните "Sample.Model.Task" элемент списка
            Mouse.Click(uISampleModelTaskListItem1, new Point(226, 225));

            // Щелкните "Редактировать задачу" кнопка
            Mouse.Click(uIРедактироватьзадачуButton1, new Point(43, 12));

            // Щелкните "OK" кнопка
            Mouse.Click(uIOKButton1, new Point(635, 23));

            // Щелкните "Ок" кнопка
            Mouse.Click(uIОКButton1, new Point(892, 3));

            // Щелкните "Выход" элемент меню
            Mouse.Click(uIВыходMenuItem, new Point(14, 9));
        }
        
        #region Properties
        public UIMyLifeRPGOrganizerXWindow UIMyLifeRPGOrganizerXWindow
        {
            get
            {
                if ((this.mUIMyLifeRPGOrganizerXWindow == null))
                {
                    this.mUIMyLifeRPGOrganizerXWindow = new UIMyLifeRPGOrganizerXWindow();
                }
                return this.mUIMyLifeRPGOrganizerXWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyLifeRPGOrganizerXWindow mUIMyLifeRPGOrganizerXWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIMyLifeRPGOrganizerXWindow : WpfWindow
    {
        
        public UIMyLifeRPGOrganizerXWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyLife RPG Organizer X";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public UIUserControlCustom UIUserControlCustom
        {
            get
            {
                if ((this.mUIUserControlCustom == null))
                {
                    this.mUIUserControlCustom = new UIUserControlCustom(this);
                }
                return this.mUIUserControlCustom;
            }
        }
        
        public UITabControlTabList UITabControlTabList
        {
            get
            {
                if ((this.mUITabControlTabList == null))
                {
                    this.mUITabControlTabList = new UITabControlTabList(this);
                }
                return this.mUITabControlTabList;
            }
        }
        
        public WpfButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIOKButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnOk";
                    this.mUIOKButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        
        public UIUserControlCustom1 UIUserControlCustom1
        {
            get
            {
                if ((this.mUIUserControlCustom1 == null))
                {
                    this.mUIUserControlCustom1 = new UIUserControlCustom1(this);
                }
                return this.mUIUserControlCustom1;
            }
        }
        
        public WpfButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WpfButton.PropertyNames.Name] = "Ок";
                    this.mUIОКButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        
        public UIUserControlCustom2 UIUserControlCustom2
        {
            get
            {
                if ((this.mUIUserControlCustom2 == null))
                {
                    this.mUIUserControlCustom2 = new UIUserControlCustom2(this);
                }
                return this.mUIUserControlCustom2;
            }
        }
        
        public UIUcTasksSettingsViewCustom UIUcTasksSettingsViewCustom
        {
            get
            {
                if ((this.mUIUcTasksSettingsViewCustom == null))
                {
                    this.mUIUcTasksSettingsViewCustom = new UIUcTasksSettingsViewCustom(this);
                }
                return this.mUIUcTasksSettingsViewCustom;
            }
        }
        
        public WpfButton UIОКButton1
        {
            get
            {
                if ((this.mUIОКButton1 == null))
                {
                    this.mUIОКButton1 = new WpfButton(this);
                    #region Условия поиска
                    this.mUIОКButton1.SearchProperties[WpfButton.PropertyNames.Name] = "Ок";
                    this.mUIОКButton1.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIОКButton1;
            }
        }
        
        public WpfCustom UIUserControlCustom3
        {
            get
            {
                if ((this.mUIUserControlCustom3 == null))
                {
                    this.mUIUserControlCustom3 = new WpfCustom(this);
                    #region Условия поиска
                    this.mUIUserControlCustom3.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.FocusItems";
                    this.mUIUserControlCustom3.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
                    this.mUIUserControlCustom3.SearchProperties[WpfControl.PropertyNames.Instance] = "2";
                    this.mUIUserControlCustom3.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIUserControlCustom3;
            }
        }
        
        public UIUserControlCustom11 UIUserControlCustom11
        {
            get
            {
                if ((this.mUIUserControlCustom11 == null))
                {
                    this.mUIUserControlCustom11 = new UIUserControlCustom11(this);
                }
                return this.mUIUserControlCustom11;
            }
        }
        
        public UIUserControlCustom21 UIUserControlCustom21
        {
            get
            {
                if ((this.mUIUserControlCustom21 == null))
                {
                    this.mUIUserControlCustom21 = new UIUserControlCustom21(this);
                }
                return this.mUIUserControlCustom21;
            }
        }
        
        public UIUserControlCustom22 UIUserControlCustom22
        {
            get
            {
                if ((this.mUIUserControlCustom22 == null))
                {
                    this.mUIUserControlCustom22 = new UIUserControlCustom22(this);
                }
                return this.mUIUserControlCustom22;
            }
        }
        
        public UIUserControlCustom31 UIUserControlCustom31
        {
            get
            {
                if ((this.mUIUserControlCustom31 == null))
                {
                    this.mUIUserControlCustom31 = new UIUserControlCustom31(this);
                }
                return this.mUIUserControlCustom31;
            }
        }
        
        public UIUserControlCustom32 UIUserControlCustom32
        {
            get
            {
                if ((this.mUIUserControlCustom32 == null))
                {
                    this.mUIUserControlCustom32 = new UIUserControlCustom32(this);
                }
                return this.mUIUserControlCustom32;
            }
        }
        
        public UIUserControlCustom4 UIUserControlCustom4
        {
            get
            {
                if ((this.mUIUserControlCustom4 == null))
                {
                    this.mUIUserControlCustom4 = new UIUserControlCustom4(this);
                }
                return this.mUIUserControlCustom4;
            }
        }
        #endregion
        
        #region Fields
        private UIUserControlCustom mUIUserControlCustom;
        
        private UITabControlTabList mUITabControlTabList;
        
        private WpfButton mUIOKButton;
        
        private UIUserControlCustom1 mUIUserControlCustom1;
        
        private WpfButton mUIОКButton;
        
        private UIUserControlCustom2 mUIUserControlCustom2;
        
        private UIUcTasksSettingsViewCustom mUIUcTasksSettingsViewCustom;
        
        private WpfButton mUIОКButton1;
        
        private WpfCustom mUIUserControlCustom3;
        
        private UIUserControlCustom11 mUIUserControlCustom11;
        
        private UIUserControlCustom21 mUIUserControlCustom21;
        
        private UIUserControlCustom22 mUIUserControlCustom22;
        
        private UIUserControlCustom31 mUIUserControlCustom31;
        
        private UIUserControlCustom32 mUIUserControlCustom32;
        
        private UIUserControlCustom4 mUIUserControlCustom4;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom : WpfCustom
    {
        
        public UIUserControlCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainWindowPersUC";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfImage UIItemImage
        {
            get
            {
                if ((this.mUIItemImage == null))
                {
                    this.mUIItemImage = new WpfImage(this);
                    #region Условия поиска
                    this.mUIItemImage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIItemImage;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIItemImage;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UITabControlTabList : WpfTabList
    {
        
        public UITabControlTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "TabControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfTabPage UIКвестыTabPage
        {
            get
            {
                if ((this.mUIКвестыTabPage == null))
                {
                    this.mUIКвестыTabPage = new WpfTabPage(this);
                    #region Условия поиска
                    this.mUIКвестыTabPage.SearchProperties[WpfTabPage.PropertyNames.Name] = "Квесты";
                    this.mUIКвестыTabPage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIКвестыTabPage;
            }
        }
        
        public WpfTabPage UIНавыкиTabPage
        {
            get
            {
                if ((this.mUIНавыкиTabPage == null))
                {
                    this.mUIНавыкиTabPage = new WpfTabPage(this);
                    #region Условия поиска
                    this.mUIНавыкиTabPage.SearchProperties[WpfTabPage.PropertyNames.Name] = "Навыки";
                    this.mUIНавыкиTabPage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIНавыкиTabPage;
            }
        }
        
        public WpfTabPage UIХарактеристикиTabPage
        {
            get
            {
                if ((this.mUIХарактеристикиTabPage == null))
                {
                    this.mUIХарактеристикиTabPage = new WpfTabPage(this);
                    #region Условия поиска
                    this.mUIХарактеристикиTabPage.SearchProperties[WpfTabPage.PropertyNames.Name] = "Характеристики";
                    this.mUIХарактеристикиTabPage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIХарактеристикиTabPage;
            }
        }
        
        public WpfTabPage UIИнформацияTabPage
        {
            get
            {
                if ((this.mUIИнформацияTabPage == null))
                {
                    this.mUIИнформацияTabPage = new WpfTabPage(this);
                    #region Условия поиска
                    this.mUIИнформацияTabPage.SearchProperties[WpfTabPage.PropertyNames.Name] = "Информация";
                    this.mUIИнформацияTabPage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIИнформацияTabPage;
            }
        }
        #endregion
        
        #region Fields
        private WpfTabPage mUIКвестыTabPage;
        
        private WpfTabPage mUIНавыкиTabPage;
        
        private WpfTabPage mUIХарактеристикиTabPage;
        
        private WpfTabPage mUIИнформацияTabPage;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom1 : WpfCustom
    {
        
        public UIUserControlCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.FocusItems";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfButton UIButtonFocusButton
        {
            get
            {
                if ((this.mUIButtonFocusButton == null))
                {
                    this.mUIButtonFocusButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIButtonFocusButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ButtonFocus";
                    this.mUIButtonFocusButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIButtonFocusButton;
            }
        }
        
        public WpfButton UIButtonFocusButton1
        {
            get
            {
                if ((this.mUIButtonFocusButton1 == null))
                {
                    this.mUIButtonFocusButton1 = new WpfButton(this);
                    #region Условия поиска
                    this.mUIButtonFocusButton1.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ButtonFocus";
                    this.mUIButtonFocusButton1.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    this.mUIButtonFocusButton1.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIButtonFocusButton1;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIButtonFocusButton;
        
        private WpfButton mUIButtonFocusButton1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom2 : WpfCustom
    {
        
        public UIUserControlCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TasksViewUC";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        
        public WpfButton UIРедактироватьзадачуButton
        {
            get
            {
                if ((this.mUIРедактироватьзадачуButton == null))
                {
                    this.mUIРедактироватьзадачуButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIРедактироватьзадачуButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Редактировать задачу";
                    this.mUIРедактироватьзадачуButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIРедактироватьзадачуButton;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        
        private WpfButton mUIРедактироватьзадачуButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIItemList : WpfList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfListItem UISampleModelTaskListItem
        {
            get
            {
                if ((this.mUISampleModelTaskListItem == null))
                {
                    this.mUISampleModelTaskListItem = new WpfListItem(this);
                    #region Условия поиска
                    this.mUISampleModelTaskListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Sample.Model.Task";
                    this.mUISampleModelTaskListItem.SearchProperties[WpfListItem.PropertyNames.Instance] = "2";
                    this.mUISampleModelTaskListItem.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUISampleModelTaskListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUISampleModelTaskListItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUcTasksSettingsViewCustom : WpfCustom
    {
        
        public UIUcTasksSettingsViewCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.UcTasksSettingsView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UcTasksSettingsView";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIOKButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnOk";
                    this.mUIOKButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom11 : WpfCustom
    {
        
        public UIUserControlCustom11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainWindowPersUC";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfImage UIItemImage
        {
            get
            {
                if ((this.mUIItemImage == null))
                {
                    this.mUIItemImage = new WpfImage(this);
                    #region Условия поиска
                    this.mUIItemImage.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIItemImage;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIItemImage;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom21 : WpfCustom
    {
        
        public UIUserControlCustom21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.FocusItems";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfButton UIButtonFocusButton
        {
            get
            {
                if ((this.mUIButtonFocusButton == null))
                {
                    this.mUIButtonFocusButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIButtonFocusButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ButtonFocus";
                    this.mUIButtonFocusButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIButtonFocusButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIButtonFocusButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom22 : WpfCustom
    {
        
        public UIUserControlCustom22(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.FocusItems";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfButton UIButtonFocusButton1
        {
            get
            {
                if ((this.mUIButtonFocusButton1 == null))
                {
                    this.mUIButtonFocusButton1 = new WpfButton(this);
                    #region Условия поиска
                    this.mUIButtonFocusButton1.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ButtonFocus";
                    this.mUIButtonFocusButton1.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    this.mUIButtonFocusButton1.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIButtonFocusButton1;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIButtonFocusButton1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom31 : WpfCustom
    {
        
        public UIUserControlCustom31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TasksViewUC";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public UIItemList1 UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList1(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList1 mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIItemList1 : WpfList
    {
        
        public UIItemList1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfListItem UISampleModelTaskListItem
        {
            get
            {
                if ((this.mUISampleModelTaskListItem == null))
                {
                    this.mUISampleModelTaskListItem = new WpfListItem(this);
                    #region Условия поиска
                    this.mUISampleModelTaskListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "Sample.Model.Task";
                    this.mUISampleModelTaskListItem.SearchProperties[WpfListItem.PropertyNames.Instance] = "3";
                    this.mUISampleModelTaskListItem.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUISampleModelTaskListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUISampleModelTaskListItem;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom32 : WpfCustom
    {
        
        public UIUserControlCustom32(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TasksViewUC";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfButton UIРедактироватьзадачуButton
        {
            get
            {
                if ((this.mUIРедактироватьзадачуButton == null))
                {
                    this.mUIРедактироватьзадачуButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIРедактироватьзадачуButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Редактировать задачу";
                    this.mUIРедактироватьзадачуButton.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIРедактироватьзадачуButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIРедактироватьзадачуButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIUserControlCustom4 : WpfCustom
    {
        
        public UIUserControlCustom4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.MainWindowAllMenu";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public UIItemMenu UIItemMenu
        {
            get
            {
                if ((this.mUIItemMenu == null))
                {
                    this.mUIItemMenu = new UIItemMenu(this);
                }
                return this.mUIItemMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIItemMenu mUIItemMenu;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "14.0.23107.0")]
    public class UIItemMenu : WpfMenu
    {
        
        public UIItemMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfMenu.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("MyLife RPG Organizer X");
            #endregion
        }
        
        #region Properties
        public WpfMenuItem UIВыходMenuItem
        {
            get
            {
                if ((this.mUIВыходMenuItem == null))
                {
                    this.mUIВыходMenuItem = new WpfMenuItem(this);
                    #region Условия поиска
                    this.mUIВыходMenuItem.SearchProperties[WpfMenuItem.PropertyNames.HelpText] = "Выход";
                    this.mUIВыходMenuItem.WindowTitles.Add("MyLife RPG Organizer X");
                    #endregion
                }
                return this.mUIВыходMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfMenuItem mUIВыходMenuItem;
        #endregion
    }
}
